apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - sync.yaml
  - automation.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra
      toolkit.fluxcd.io/role: automation
