apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-tenant
  namespace: kube-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-tenant
  interval: 5m
  retryInterval: 3m
  path: ./tenants/use-case/talk-to-your-data
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  patches:
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: toolkit.fluxcd.io/role=automation