apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: kube-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
    replicator.v1.mittwald.de/replicate-to: ".*"
data:
  ENVIRONMENT: "staging"
  STRATIO_SIZE: "small"
  GIT_BRANCH: "main"
  CLUSTER_NAME: "eosdev2"
  CLUSTER_DOMAIN: "k8s.eosdev2.labs.stratio.com"
