apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - rbac.yaml
  - source.yaml
  - sis.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: system-services
