---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpa-configs
spec:
  serviceAccountName: flux-system-services
  dependsOn:
    - name: vpa-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system-services
  path: components/vpa/configs/${ENVIRONMENT}
